services:
  custom-reject-mailcow:
    build:
      context: ./milter
    depends_on:
      - postfix-mailcow
      - rspamd-mailcow
    stop_grace_period: 45s
    environment:
      - TZ=${TZ}
    restart: always
    ports:
      - "${CUSTOM_MILTER_PORT:-127.0.0.1:12345}:12345"
    networks:
      mailcow-network:
        aliases:
          - custom_reject
